[package]
name = "swarm-work-verify"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenv = "0.15.0"
meval = "0.2.0"
serde = "1.0.228"
serde_json = "1.0.149"
swarms-rs = "0.2.1"
tokio = "1.49.0"
tracing-subscriber = "0.3.22"
